/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_256: THREE.Mesh
    Object_258: THREE.Mesh
    Object_6: THREE.Mesh
    Object_10: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_261: THREE.Mesh
    Object_263: THREE.Mesh
  }
  materials: {
    ['1.001']: THREE.MeshPhysicalMaterial
    ['1.002']: THREE.MeshStandardMaterial
    lightAndCablewhitePlastic: THREE.MeshStandardMaterial
    JokerMat: THREE.MeshStandardMaterial
    ['insulation.001']: THREE.MeshStandardMaterial
    ['cement.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/untitled.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-2.249, 0.182, 0]} rotation={[1.723, 0, -1.528]} scale={0.2}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.JokerMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.JokerMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.JokerMat}
        />
      </group>
      <group position={[-0.186, 0, 0.04]} rotation={[Math.PI / 2, 0, 0]} scale={0.003}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_261.geometry}
          material={materials['insulation.001']}
          position={[0, 0, -900]}
          rotation={[-Math.PI, 0, 0]}
          scale={[0.994, 0.994, 0.998]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_263.geometry}
          material={materials['cement.001']}
          position={[0, 0, -450]}
          scale={[13.725, 16.688, 8.839]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_256.geometry}
        material={materials['1.001']}
        position={[0.094, 0.217, -0.78]}
        rotation={[0, -1.002, -Math.PI / 2]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_258.geometry}
        material={materials['1.002']}
        position={[0.084, 0.213, -0.784]}
        rotation={[0, -1.012, -Math.PI / 2]}
        scale={0.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.lightAndCablewhitePlastic}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  )
}

useGLTF.preload('/untitled.glb')